spring:
  application:
    name: device-cache
  redis:
    database: 0
    host: 192.168.1.201
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
server:
  port: 8115

cache:
  data-key: device-cache-data
  server-path: 192.168.1.201
  server-port: 20005